language: python
python:
  - "3.6"

install:
    - pip install -r requirements.txt   
env:
  - DB=sqlite
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
  - pep8 --show-source --show-pep8 hc/

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: never

cache: pip
