language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
addons:
  postgresql: "10.1"

services:
  - postgresql

before_script:
  - psql -c 'create database hc;' -U postgres
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
  - pep8 --show-source --show-pep8 .
after_success: coveralls
cache: pip
