language: python
python:
  - "2.7"
  - "3.4"
install:
    - pip install -r requirements.txt
env:
  - DB=postgres
addons:
  postgresql: "9.4"
script:
  - pep8 --show-source --show-pep8 hc/
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
