language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
    - pip install pep8
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
addons:
  postgresql: "10.1"
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
  - pep8 --show-source --show-pep8 hc/front/tests/
after_success: coveralls
cache: pip
