language: python
python:
  - "3.6"
branches:
    only:
        - ch-tests-for-accounts-153114587
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock
services:
  - postgres

addons:
  postgresql: "10.1"

before_script:
  - psql -c 'create database hc;' -U postgres
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
  - pep8 --show-source --show-pep8 . || exit 0
after_success: coveralls
cache: pip
