# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook'), ('hipchat', 'HipChat'), ('slack', 'Slack'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('victorops', 'VictorOps')], max_length=20),
        ),
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.CharField(blank=True, error_messages={'blank': 'Please make sure name is string!'}, max_length=100),
        ),
    ]
