# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171218_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='alert_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
