# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_checkreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkreport',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
