# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20171219_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='api_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, help_text='AfricasTalking username', max_length=20),
        ),
        migrations.AlterField(
            model_name='check',
            name='alert_after',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
