# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20171219_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
