# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20171220_1519'),
        ('api', '0028_checkreport_timestamp'),
    ]

    operations = [
    ]
