# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20171221_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkreport',
            name='chk',
        ),
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.CharField(blank=True, error_messages={'blank': 'Please make sure name is string!'}, max_length=100),
        ),
        migrations.DeleteModel(
            name='CheckReport',
        ),
    ]
