# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20171219_1520'),
        ('api', '0033_auto_20171221_0600'),
    ]

    operations = [
    ]
